### ISSUE TITLE
Signs dont seem to work

### ISSUE THREAD

**Issue by JeffRabbitYT** [Misat11/BedWars#28]
Players with no permissions can do /bw join but when clicking on a sign (which works for Staff) nothing happens.

The server is in 1.14.3
Spigot version: I dunno
BedWars version: 0.1.5

Plugins:
Ultimate_vote, DeathmessagesPrime,
BukkitCore, WorldEdit, Multiverse-Core
OldCombatMechanics, TitleWelcomeMessage,
UReport, PlayerServer, Multiverse-Portals
PermissionsEx, ChatControl, Essentials,
AdvancedBan, Antibot, EssentialsChat,
StaffChatReloaded, Vault, Bedwars,
WorldGuard, ProtocolLib, BuycraftX
KillerMoney, EssentialsSpawn.

I didn't edit Config for Shop files

Config.yml:
```
# Locale (en, cs, ru)
locale: en

allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
spectator-gm3: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true

# Commands whitelist
allowed-commands:
- "/help"

# Ignored blocks (Farm blocks)
farmBlocks:
  enable: true
  blocks:
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS

# Scoreboard settings
scoreboard:
  enable: true
  title: "§a%game%§r - %time%"
  bedLost: "§c\u2718"
  bedExists: "§a\u2714"
  teamTitle: "%bed%%color%%team%"
  
# Title speed
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
  
# Items
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  
# Vault rewards
vault:
  enable: true
  reward:
    kill: 5
    win: 20
  
# Resources
resources:
  bronze:
    material: BRICK
    interval: 1
    name: "Bronze"
    translate: "resource_bronze"
    color: DARK_RED
    spread: 1.0
  iron:
    material: IRON_INGOT
    interval: 10
    name: "Iron"
    translate: "resource_iron"
    color: GRAY
    spread: 1.0
  gold:
    material: GOLD_INGOT
    interval: 20
    name: "Gold"
    translate: "resource_gold"
    color: GOLD
    spread: 1.0
    
# Sounds (look to github src/main/java/misat11/bw/utils/Sounds.java for possible values)
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  
# Game effects
game-effects:
  end: 
    type: Firework
    power: 1
    effects:
    - ==: org.bukkit.FireworkEffect
      type: BALL
      fade-colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      colors:
      - ==: org.bukkit.Color
        RED: 255
        GREEN: 255
        BLUE: 255
      trail: false
      flicker: false
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
  
  
# Lobby scoreboard
lobby-scoreboard:
  enabled: true

  title: "§eBEDWARS"
  
  content:
    - " "
    - "§fMap: §2%arena%"
    - "§fPlayers: §2%players%§f/§2%maxplayers%"
    - " "
    - "§fWaiting ..."
    - " "
  
# Statistics  
statistics:
  enabled: true
  type: 'yaml'
  show-on-game-end: true
  bed-destroyed-kills: false
  
  # Scores configuration
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
  
# database (currently only mysql) configuration
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
  
# Bossbar
bossbar:
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
    
# Holograms
holograms:
   enabled: true  
   headline: "Your §eBEDWARS§f stats"
   
# Chat
chat:
   override: true
   format: "<%teamcolor%%name%§r> "
   separate-game-chat: false
   send-death-messages-just-in-game: true
   
# Command rewards (possible placeholders {player},{score})
rewards:
   enabled: false
   # Player won
   player-win:
   - /example {player} 200
   # Every player in game
   player-end-game:
   - /example {player} {score}
   # Player destroyed target block of other team
   player-destroy-bed:
   - /example {player} {score}  
   # Player killed other player
   player-kill:
   - /example {player} 10
   
# Give items
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []

# Shop lore
lore:
   generate-automatically: true # can be set individual to items
   text:
   - "§7Price:"
   - "§7%price% %resource%"
   - "§7Amount:"
   - "§7%amount%"
   
# Do not edit this!!!
version: 2
```

Shop.yml:
```
# DO NOT EDIT THIS VARIABLE!!!
version: 2

# And this you can edit of course.
data:
#-   stack:
#      ==: org.bukkit.inventory.ItemStack 
#      v: 1519
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        v: 1519
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_CHESTPLATE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Armor"
        lore:
        - "Protect yourself with armor! Click here."
    items:
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_LEGGINGS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_BOOTS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 7
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - price: 10
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Helm
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
  
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_SWORD
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Swords"
        lore:
        - "Click here to get sword for attacking your enemies"
    column: center
    items:
    - price: 8
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STICK
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price: 7
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 3
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            KNOCKBACK: 1
    - price: 15
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_AXE
        display-name: "Axe of Infinity"
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
            DURABILITY: 1
            KNOCKBACK: 1
    
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: BOW
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Bows"
        lore:
        - "Prove yourself as a marksman with these wonderful bows"
    column: right
    items:
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
    - price: 7
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_DAMAGE: 1
    - price: 13
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_DAMAGE: 2
    - price: 14
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_FIRE: 1
    - price: 15
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_FIRE: 1
            ARROW_KNOCKBACK: 1
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ARROW
        amount: 1 
        
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: COOKED_PORKCHOP
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Eat"
        lore:
        - "Are you hungry? Get something to eat."
    row: 3
    column: 2
    items:
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: COOKED_PORKCHOP
        amount: 2
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_APPLE
        amount: 1
    - price: 5
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BREAD
        amount: 10

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: POTION
      meta:
        ==: ItemMeta
        meta-type: POTION
        display-name: "Drinks"
        lore:
        - "Not enough? Use these potions and you'll feel better!"
        potion-type: strength
    row: 3
    column: 6
    items:
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: healing
      price: 3
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strong_healing
      price: 5
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: swiftness
      price: 7
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strength
      price: 1
      price-type: gold
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: regeneration
      price: 3
      price-type: gold
      
        

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: SANDSTONE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Blocks"
        lore:
        - "Destroy others blocks? Use these pickaxes."
    linebreak: before
    items:
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CUT_SANDSTONE
        amount: 2
    - price: 7
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: END_STONE
        amount: 3
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_BLOCK
        amount: 1
    - price: 15
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GLOWSTONE
        amount: 4
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GLASS
            
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: TNT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Useful Stuff"
        lore:
        - "Looking for useful stuff? Here are some!"
    column: center
    items:
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHEST
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ENDER_CHEST
    - price: 7
      price-type: iron
      properties:
      - name: "WarpPowder"
        delay: 6
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: GUNPOWDER
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Warp Powder"
          lore:
          - "When using this powder you'll get"
          - "teleported to you spawn point within 6 seconds"
          - "Warning: Any movement will stop the process"
    - price: 3
      price-type: iron
      properties:
      - name: "Trap"
        data:
        - sound: ENTITY_SHEEP_AMBIENT
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: STRING
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Trap"
          lore:
          - "Get informed if an enemy steps on your trap"
          - "and your enemy won't be able to move properly."

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_PICKAXE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Pickaxes"
        lore:
        - "Destroy others blocks? Use these pickaxes."
    column: right
    items:
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 1
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 2
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 3
```
